name: Build test orchestrator

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    container:
      image: rust:1.85-bookworm

    steps:
      - name: Cleanup
        uses: FraBle/clean-after-action@b4cc12128d2ad0fd0feb639ef8c48c97f5b75dbb

      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Build debug
        run: cargo build --verbose

      - name: Run tests debug
        run: cargo test --verbose

      - name: Build release
        run: cargo build --release --verbose

      - name: Run tests release
        run: cargo test --release --verbose