name: Validate PR's

on:
  pull_request:

jobs:
    validate-pr:
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: ./.github/workflows/build-test-orchestrator.yml
        with:
          make_release: false
